In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
playstore = pd.read_csv("https://raw.githubusercontent.com/gdv/foundationsCS-2018/master/ex-data/project/googleplaystore.csv")
reviews = pd.read_csv("https://raw.githubusercontent.com/gdv/foundationsCS-2018/master/ex-data/project/googleplaystore_user_reviews.csv")

# punto 1 Convert the app sizes to a number

In [2]:
play = pd.DataFrame(playstore)

In [3]:
play[['firstcol', 'secondcol']] = play['Size'].str.extract('(\d+\.?\d*)([A-Za-z]*)', expand = True)
Size = pd.Series(play['Size'])

In [4]:
numero = pd.Series(play['firstcol'])
valore = pd.Series(play['secondcol'])
a = 0
b = 0

In [5]:
for i in range(0,10841):
    b = 0
    for j in range(0,10841):
        if a == b:
            if valore[j] == 'M':
                Size[a] = float(numero[i])*1000000
            if valore[j] == 'k':
                Size[a] = float(numero[i])*1000
            if valore[j] == 'G':
                Size[a] = float(numero[i])*1000000000
        b = b+1
    a = a+1

In [6]:
play['Size'] = Size
Size.head()

0    1.9e+07
1    1.4e+07
2    8.7e+06
3    2.5e+07
4    2.8e+06
Name: Size, dtype: object

# punto 2 Convert the number of installs to a number

In [7]:
inst = pd.Series(play['Installs'])

In [8]:
for i in range(0,len(play.Installs)):
    inst[i] = re.sub('[+,]','',play.Installs[i])

In [9]:
play['Installs'] = inst
inst

0           10000
1          500000
2         5000000
3        50000000
4          100000
5           50000
6           50000
7         1000000
8         1000000
9           10000
10        1000000
11        1000000
12       10000000
13         100000
14         100000
15           5000
16         500000
17          10000
18        5000000
19       10000000
20         100000
21         100000
22         500000
23         100000
24          50000
25          10000
26         500000
27         100000
28          10000
29         100000
           ...
10811         100
10812        1000
10813       10000
10814       50000
10815      500000
10816         100
10817      100000
10818       10000
10819        5000
10820        1000
10821          50
10822          10
10823         100
10824       10000
10825         100
10826     5000000
10827        5000
10828       10000
10829       10000
10830      100000
10831        5000
10832      100000
10833        1000
10834         500
10835          10
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs, Length: 10841, dtype: object

# punto 3 Transform “Varies with device” into a missing value

In [10]:
play = play.replace("Varies with device",np.nan)

# punto 4 Convert Current Ver and Android Ver into a dotted number (e.g. 4.0.3 or 4.2)

In [11]:
cur_ver=pd.Series(play['Current Ver'])
and_ver=pd.Series(play['Android Ver'])
cur_ver_1=pd.Series([''])
and_ver_1=pd.Series([''],index=[0])

In [12]:
x = ""
for i in cur_ver:
    try:
        x = re.compile('\d+[\d\.]+\d').match(str(i)).group()
        cur_ver_1.set_value(max(cur_ver_1.index) + 1,  x)

    except:
        x = np.nan
        cur_ver_1.set_value(max(cur_ver_1.index) + 1,  x)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':

In [13]:
cur_ver_1.head()

0
1    1.0.0
2    2.0.0
3    1.2.4
4      NaN
dtype: object

In [14]:
x = ""
for i in and_ver:
    try:
        x = re.compile('\d+[\d\.]+\d').match(str(i)).group()
        and_ver_1.set_value(max(and_ver_1.index) + 1,  x)

    except:
        x = np.nan
        and_ver_1.set_value(max(and_ver_1.index) + 1,  x)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':

In [15]:
and_ver_1.head()

0
1    4.0.3
2    4.0.3
3    4.0.3
4      4.2
dtype: object

# punto 5 Remove the duplicates

In [16]:
#ipotizzo che i duplicati siano solo del nome
play = play.drop(play[play.Rating > 5].index)
play = play.drop_duplicates(subset=['App'], keep = 'first', inplace = False).sort_index().reset_index(drop=True)

In [17]:
play['App'].nunique() #mi conta i valori unici che ho per ogni colonna del mio dataframe (play)

9659

In [18]:
lenght = len(play['App'])
lenght
#il numero di elementi unici e quelli presenti nel dataframe "clean" sono uguali, quindi i duplicati sono stati rimossi.

9659

# punto 6 For each category, compute the number of apps

In [19]:
sub_play = play[['App','Category']]
sub_group = sub_play.groupby('Category').count()
sub_group

                      App
Category
ART_AND_DESIGN         64
AUTO_AND_VEHICLES      85
BEAUTY                 53
BOOKS_AND_REFERENCE   222
BUSINESS              420
COMICS                 56
COMMUNICATION         315
DATING                171
EDUCATION             119
ENTERTAINMENT         102
EVENTS                 64
FAMILY               1832
FINANCE               345
FOOD_AND_DRINK        112
GAME                  959
HEALTH_AND_FITNESS    288
HOUSE_AND_HOME         74
LIBRARIES_AND_DEMO     84
LIFESTYLE             369
MAPS_AND_NAVIGATION   131
MEDICAL               395
NEWS_AND_MAGAZINES    254
PARENTING              60
PERSONALIZATION       376
PHOTOGRAPHY           281
PRODUCTIVITY          374
SHOPPING              202
SOCIAL                239
SPORTS                325
TOOLS                 827
TRAVEL_AND_LOCAL      219
VIDEO_PLAYERS         163
WEATHER                79

# punto 7 For each category, compute the average rating

In [20]:
play_rat = play[['Rating','Category']]
play_rat = play_rat.groupby('Category').mean()
play_rat.head()

                       Rating
Category
ART_AND_DESIGN       4.357377
AUTO_AND_VEHICLES    4.190411
BEAUTY               4.278571
BOOKS_AND_REFERENCE  4.344970
BUSINESS             4.098479

# punto 8 Create two dataframes: one for the genres and one bridging apps and genres. So that, for instance, the app Pixel Draw - Number Art Coloring Book appears twice in the bridging table, once for Art & Design, once for Creativity

In [21]:
#creo prima quello per i generi
def uniq(input):
    output = []
    for x in input:
        if x not in output:
            output.append(x)
    return output

In [22]:
genlist = uniq(play['Genres'])
genlistdf = pd.DataFrame(genlist)

In [23]:
split = genlistdf[0].str.split(";", n = 1, expand = True) 
lista = uniq(split[0])

In [24]:
def uniq2(input,lista):
    output = lista
    for x in input:
        if x not in output:
            output.append(x)
    return output

In [25]:
complete = uniq2(split[1],lista)
completedf = pd.DataFrame(complete)
Genere = completedf.dropna()
Genere

                          0
0              Art & Design
1           Auto & Vehicles
2                    Beauty
3         Books & Reference
4                  Business
5                    Comics
6             Communication
7                    Dating
8                 Education
9             Entertainment
10                   Events
11                  Finance
12             Food & Drink
13         Health & Fitness
14             House & Home
15         Libraries & Demo
16                Lifestyle
17                Adventure
18                   Arcade
19                   Casual
20                     Card
21                   Action
22                 Strategy
23                   Puzzle
24                   Sports
25                    Music
26                     Word
27                   Racing
28               Simulation
29                    Board
30                   Trivia
31             Role Playing
32              Educational
33            Music & Audio
34  Video Players & Editors
35                  Medical
36                   Social
37                 Shopping
38              Photography
39           Travel & Local
40                    Tools
41          Personalization
42             Productivity
43                Parenting
44                  Weather
45         News & Magazines
46        Maps & Navigation
47                   Casino
49             Pretend Play
50               Creativity
51       Action & Adventure
52            Music & Video
53              Brain Games

In [26]:
#creo il secondo che fa da ponte
App = play[['App','Genres']]
supp = App['Genres'].str.split(';', n = 1, expand = True)
App['first'] = supp[0]
App['second'] = supp[1]
App.drop(columns = ['Genres'], inplace = True) #elimino la colonna

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [27]:
parte1 = App[['App','first']]
parte2 = App[['App','second']]
parte2 = parte2.dropna()
parte2.rename(columns={'second': 'first'}, inplace=True)
frames = [parte1,parte2]
Genres_App = pd.concat(frames)
Genres_App = Genres_App.sort_values(['App'])
Genres_App.rename(columns={'first': 'Genre'}, inplace=True)

In [28]:
Genres_App.loc[Genres_App['App'] == 'Hair saloon - Spa salon']

                          App         Genre
9331  Hair saloon - Spa salon        Casual
9331  Hair saloon - Spa salon  Pretend Play

# punto 9 For each genre, create a new column of the original dataframe. The new columns must have boolean values (True if the app has a given genre)

In [29]:
for i in Genere[0]:
    play[i] = False
play[['g1','g2']] = play['Genres'].str.split(';',expand=True)
clean1 = play

In [30]:
for i in Genere[0]:
    clean1[i].loc[clean1["g1"]==i] = True
for i in Genere[0]:
    clean1[i].loc[clean1["g2"]==i] = True

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [31]:
clean1.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,News & Magazines,Maps & Navigation,Casino,Pretend Play,Creativity,Action & Adventure,Music & Video,Brain Games,g1,g2
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,1.9e+07,10000,Free,0,Everyone,Art & Design,...,False,False,False,False,False,False,False,False,Art & Design,None
1,Coloring book moana,ART_AND_DESIGN,3.9,967,1.4e+07,500000,Free,0,Everyone,Art & Design;Pretend Play,...,False,False,False,True,False,False,False,False,Art & Design,Pretend Play
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7e+06,5000000,Free,0,Everyone,Art & Design,...,False,False,False,False,False,False,False,False,Art & Design,None
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,2.5e+07,50000000,Free,0,Teen,Art & Design,...,False,False,False,False,False,False,False,False,Art & Design,None
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8e+06,100000,Free,0,Everyone,Art & Design;Creativity,...,False,False,False,False,True,False,False,False,Art & Design,Creativity

# punto10 For each genre, compute the average rating. What is the genre with highest average?

In [32]:
clean2= clean1
Genere.join(clean2["Rating"], sort = False).groupby(Genere[0]).mean().sort_values(by = 'Rating', ascending = False)

                         Rating
0
Music                       4.8
Word                        4.7
Strategy                    4.7
News & Magazines            4.7
Lifestyle                   4.7
Entertainment               4.7
Social                      4.7
Sports                      4.7
Photography                 4.7
Beauty                      4.7
Video Players & Editors     4.7
Music & Video               4.6
Casual                      4.6
Health & Fitness            4.6
Maps & Navigation           4.6
Books & Reference           4.5
Personalization             4.5
Adventure                   4.5
Educational                 4.5
Finance                     4.4
House & Home                4.4
Education                   4.4
Events                      4.4
Productivity                4.4
Comics                      4.4
Business                    4.3
Arcade                      4.3
Music & Audio               4.2
Tools                       4.2
Weather                     4.2
Pretend Play                4.2
Trivia                      4.2
Casino                      4.2
Food & Drink                4.2
Racing                      4.1
Role Playing                4.1
Shopping                    4.1
Action                      4.1
Dating                      4.1
Board                       4.1
Art & Design                4.1
Creativity                  4.0
Card                        4.0
Travel & Local              4.0
Simulation                  3.9
Brain Games                 3.9
Auto & Vehicles             3.9
Parenting                   3.8
Medical                     3.8
Action & Adventure          3.8
Communication               3.8
Libraries & Demo            3.2
Puzzle                      NaN

# punto11 For each app, compute the approximate income, obtain as a product of number of installs and price.

In [33]:
play['Price'].value_counts().sort_index

<bound method Series.sort_index of 0          8903
$0.99       145
$2.99       124
$1.99        73
$4.99        70
$3.99        57
$1.49        46
$5.99        26
$2.49        25
$9.99        19
$399.99      12
$6.99        11
$14.99        9
$4.49         9
$7.99         7
$3.49         7
$19.99        5
$5.49         5
$8.99         5
$6.49         5
$29.99        5
$12.99        4
$2.00         3
$1.00         3
$24.99        3
$11.99        3
$17.99        2
$10.99        2
$1.70         2
$8.49         2
           ...
$89.99        1
$3.95         1
$109.99       1
$379.99       1
$3.04         1
$4.59         1
$18.99        1
$4.60         1
$79.99        1
$2.50         1
$3.88         1
$15.99        1
$1.26         1
$1.76         1
$4.84         1
$15.46        1
$25.99        1
$19.90        1
$394.99       1
$1.97         1
$30.99        1
$2.90         1
$1.75         1
$2.95         1
$5.00         1
$4.77         1
$2.60         1
$1.29         1
$200.00       1
$74.99        1
Name: Price, Length: 92, dtype: int64>

In [34]:
revenue = []
play['Price'].replace('Free',0)
inst = play['Installs']
price = play['Price']
lenght = len(play['App'])

In [35]:
inst1 = pd.Series(inst).replace('Free',0)
price1 = pd.Series(price).replace('Free',0)
price1 = pd.Series(price1).replace('Everyone',0)

In [36]:
for i in range(0,lenght):
    revenue.append(int(inst1[i])*(float(price1[i].replace('$',''))))
revenue

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 499000.0,
 499000.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 399000.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 39900.0,
 6990.0,
 74.5,
 299.0,
 399.0,
 799.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3990.0,
 5990.0,
 1995000.0,
 399000.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 499000.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 299000.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 ...]

# punto12 For each app, compute its minimum and maximum Sentiment_polarity

In [37]:
reviews = reviews.dropna().sort_index().reset_index(drop=True)

In [38]:
#massimo
massimo = reviews.groupby(['App']).max().sort_values(['Sentiment_Polarity'], ascending = False)
massimo.head()

,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
App,,,,
10 Best Foods for You,nice super get,Positive,1.0,1.00
Cache Cleaner-DU Speed Booster (booster & cleaner),actually works stated. Ads function without le...,Positive,1.0,1.00
Calorie Counter - Macros,great ive using year changed phone (from galax...,Positive,1.0,0.95
"Calm - Meditate, Sleep, Relax",worked fine I paid $60 subscription fee locked...,Positive,1.0,1.00
Flippy Campus - Buy & sell on campus at a discount,think u add features,Positive,1.0,1.00

In [39]:
#minimo
minimo = reviews.groupby(['App']).min().sort_values(['Sentiment_Polarity'],ascending = True)
minimo.head()

,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
App,,,,
"BestCam Selfie-selfie, beauty camera, photo editor",Ad ch feklyf,Negative,-1.0,0.0
"BuzzFeed: News, Tasty, Quizzes","Amazing app, I wish easier find post things. I...",Negative,-1.0,0.0
Extreme Match,A fun game.,Negative,-1.0,0.0
"Expedia Hotels, Flights & Car Rental Travel Deals",Awesome layout super easy. My fiance I getting...,Negative,-1.0,0.0
Eat Fit - Diet and Health Free,...Really? There way input dietary restriction...,Negative,-1.0,0.0